> library(readxl)
> PCB1 <- read_excel("E:/Jobs/1083636/PCB1.xlsx")
> View(PCB1)
> library(readxl)
> PCB2 <- read_excel("E:/Jobs/1083636/PCB2.xlsx")
> View(PCB2)
> summary(PCB1)
> summary(PCB2)
> plot(PCB1)
> plot(PCB2)
> cor(PCB1)
> cor(PCB2)
> PCB1model <- lm(formula = PCB ~ Age, data = PCB1)
> summary(PCB1model)
> PCB2model <- lm(formula = PCB ~ Age, data = PCB2)
> summary(PCB2model)